version: "3.9"
services:
  # Base de donnÃ©es MySQL
  database:
    image: mysql:8.0
    container_name: glycopilot-db
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -h localhost -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1' || exit 1"
        ]
      interval: 5s
      timeout: 5s
      retries: 12

  # Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    image: glycopilot-backend
    container_name: glycopilot-back
    ports:
      - "8006:8000"
    volumes:
      - ./backend:/app
    depends_on:
       database:
         condition: service_healthy
    restart: unless-stopped
    command: >
      sh -C "
      echo 'waiting for mysql to be ready....';
      echo 'MYSQL is up, running migration ....';
      python manager.py migrate;
      python manger.py runserver 0.0.0.0:80000
      "
    
  

  # Frontend React Native
  frontend:
    image: node:20-alpine
    container_name: glycopilot-front
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npx expo start --lan"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  mysql_data:
